---
title: "Course Materials"
---

On this page you will find the lecture slides and videos as well as links to papers with textbook-like applications of each technique. You can find more resources on learning R and learning econometrics and causal inference under [Resources](resources.qmd).

## 0 Housekeeping

#### [Slides](/slides/0 Housekeeping/slides_0_housekeeping.pdf)


## 1 Foundations of Causal Inference: DAGs

#### [Slides](/slides/1 Causality/slides_1_causality.pdf)


#### Videos

These two videos explain the foundations of causal inference based on directed acyclic graphs (DAGs)

{{< video https://youtu.be/tUz2yl2QEbY >}}

{{< video https://youtu.be/9QJUvVB4lcI >}}




## 2 Regression Recap


## 3 Randomised Experiments and the Potential Outcomes Framework



## 4 Matching

#### Slides



## 5 Instrumental Variables

#### Slides

#### Videos

The following five videos cover instrumental variables and applications:  

{{< video https://youtu.be/2dl2FTik-y4 >}}

{{< video https://youtu.be/et-8a3_cFUM >}}

{{< video https://youtu.be/s0YOQnouYO4 >}}

{{< video https://youtu.be/JU1SaKbRhdM >}}

{{< video https://youtu.be/aC_2Sn-IxTk >}}



## 6 Regression Discontinuity

#### Slides

#### Videos

{{< video https://youtu.be/I2IJcyCLVlc >}}

{{< video https://youtu.be/nYfF80pWeFc >}}

{{< video https://youtu.be/kyMdBi806bk >}}

## 7 Difference-in-Differences

#### Slides

#### Videos

{{< video https://youtu.be/yM5tLON-meM >}}

{{< video https://youtu.be/zKk6U4NcgsU >}}

{{< video https://youtu.be/NUwxMqZAMjI >}}


## 8 Synthetic Control


#### Slides

#### Videos

{{< video https://youtu.be/vmx3R8emVjQ >}}

{{< video https://youtu.be/RwbFdga1V4Q >}}


