---
title: "Resources"
---

On this page I provide links to learning resources I find very useful. This is surely not an exhaustive list. I'll add to this list when I come across interesting resources.

## Learning R

R comes with a steep learning curve but opens up a lot of possibilities for its users. You don't need to learn each and every command --- no one is able to do that. The best you can do is learn the basics, get started with a project and learn by doing. And then practice, practice, practice.

There are almost endless resources on R on the web. Here are some resources I recommend:

#### Videos

-   [Nick Huntington-Klein](https://www.youtube.com/@NickHuntingtonKlein) has excellent videos on [R for econometrics](https://www.youtube.com/playlist?list=PLcTBLulJV_AIuXCxr__V8XAzWZosMQIfW) and many other topics.

-   [Albert Rapp's website](https://albert-rapp.de/) and [YouTube channel](https://www.youtube.com/@rappa753) is a treasure trove for tips and tricks with R, especially for data wrangling, visualisation, and outputs with Quarto.

#### Textbooks and websites

-   Here is a [free e-book](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) with an introduction to base R. R has gotten a lot more user friendly with the introduction of tidyverse. However, if you want to become proficient in R, knowing base R is very helpful.

-   [R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund is THE standard textbook for working with tidyverse.

-   For econometrics, I recommend two e-books: 1) [Introduction to Econometrics with R](https://www.econometrics-with-r.org/), an introductory e-book based on the Stock & Watson textbook, created by Christoph Hanck, Martin Arnold, Alexander Gerber, and Martin Schmelzer. 2) [Introduction to Econometrics with R](https://scpoecon.github.io/ScPoEconometrics/), a free e-book by a team of professors from Sciences Po (Florian Oswald, Vincent Viers, Jean-Marc Robin, Pierre Villedieu, Gustave Kenedi). The book combines everything you need: an introduction to R, econometric theory, coding examples, etc.

-   The [R Graph Gallery](https://r-graph-gallery.com/index.html) by Yan Holtz provides examples (visual and code) for pretty much any graph type under the sun.

-   [Telling Stories with Data](https://tellingstorieswithdata.com/) by Rohan Alexander is a free e-book aimed at data scientists. It offers lots of excellent examples about workflows, exploratory analysis, modeling and applications.

-   [Allison Horst's page on data wrangling with dplyr](https://allisonhorst.shinyapps.io/dplyr-learnr) is excellent. Come for the coding, stay for the penguin illustrations.

-   R is great for **text analysis**. You can learn [tidytext in this excellent tutorial by Julia Silge](https://juliasilge.shinyapps.io/learntidytext/). A more comprehensive package on text analysis is [Quanteda](http://quanteda.io/), which has been co-written and is co-maintained by [Stefan Müller](https://muellerstefan.net/). Stefan is also based at UCD and does very cool work at the intersection of political science and data science. [See here for an example](https://pollingindicator.com/).

-   [Grant McDermott's materials on Data Science for Economists](https://github.com/uo-ec607/lectures) have lots of interesting material on workflow, processing of large data (high-performance computing, Spark, Docker), and database management.

-   [Jon Hersh's course on Machine Learning for Economists](https://github.com/jonhersh/BUS696/tree/master/slides)covers the basics of machine learning in a very intuitive way.

## 

## Causal Inference

#### General

-   The Nobel Prize 2021 was given to three masters of causal inference: [David Card](https://youtu.be/wD48p6m8U-8), [Joshua Angrist](https://youtu.be/vEBUER-l0yQ), and [Guido Imbens](https://youtu.be/yTrVg-t8O8A). Here is a [video of a lecture to UCD undergraduate students](https://www.youtube.com/watch?v=yG2__HMQpTQ) I've given the day after the prize was announced.

-   It is difficult to stay up to date with all the new methods in applied econometrics. Here is a fantastic public good by [Christine Cai](https://christinecai.github.io/), who maintains a document with abstracts and references of methods papers of the last 5-6 years. [Link here](https://christinecai.github.io/PublicGoods/applied_micro_methods.pdf).

-   Paul Goldsmith-Pinkham has an excellent course on applied empirical methods (basically causal inference), with [YouTube videos](https://www.youtube.com/playlist?list=PLWWcL1M3lLlojLTSVf2gGYQ_9TlPyPbiJ) and [lecture slides](https://github.com/paulgp/applied-methods-phd).

-   Want to use causal inference with Python? Check out Matheus Facure's free e-book [Causal Inference for the Brave and True](https://matheusfacure.github.io/python-causality-handbook/landing-page.html).

#### Specific Methods

-   [Jonathan Roth](https://www.jonathandroth.com/did-resources/) provides excellent slides on new **diff-in-diff** methods, along with coding exercises and R packages. Also, see [Ajad Naqvi's website](https://asjadnaqvi.github.io/DiD/) listing the various diff-in-diff packages in R, Stata and Julia.
-   [Matias D. Cattaneo](https://arxiv.org/search/stat?searchtype=author&query=Cattaneo%2C+M+D), [Nicolas Idrobo](https://arxiv.org/search/stat?searchtype=author&query=Idrobo%2C+N), [Rocio Titiunik](https://arxiv.org/search/stat?searchtype=author&query=Titiunik%2C+R) have an [excellent review article](https://arxiv.org/abs/2301.08958) on **regression discontinuity designs**.
-   [Peter Hull's course materials](https://github.com/Mixtape-Sessions/Instrumental-Variables) on **instrumental variables**.
